export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const SET_AUTH_USER = 'SET_AUTH_USER';
export const LOAD_ALL_PHOTOS_SUCCESS = 'LOAD_ALL_PHOTOS_SUCCESS';

